//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using WebApi2.Models.Formulario;
    
    public partial class categoria
    {
        public categoria()
        {
            this.formulario = new HashSet<formulario>();
        }
    
        [Key]
        public int Idn_Categoria { get; set; }
        public string Dsc_Nome { get; set; }
        public Nullable<System.DateTime> Dta_Categoria { get; set; }
        public string Dsc_Status { get; set; }
    
        public virtual ICollection<formulario> formulario { get; set; }
    }
}
