//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class evento
    {
        [Key]
        public int Idn_Evento { get; set; }
        public Nullable<int> Idn_Pedido { get; set; }
        public string Dsc_Nome { get; set; }
        public Nullable<System.DateTime> Dta_Evento { get; set; }
        public string Dsc_Evento { get; set; }
        public string Dsc_Perfil { get; set; }
    
        public virtual pedido pedido { get; set; }
    }
}
