//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi2.Models.Formulario
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class formulario
    {
        public formulario()
        {
            this.pedido = new HashSet<pedido>();
            this.roteador = new HashSet<roteador>();
        }

        [Key]
        public int Idn_Formulario { get; set; }
        public int Idn_Grupo { get; set; }
        public string Dsc_Nome { get; set; }
        public Nullable<System.DateTime> Dta_Formulario { get; set; }
        public Nullable<int> Idn_Categoria { get; set; }
        public string Dsc_Status { get; set; }
    

        public virtual categoria categoria { get; set; }
        public virtual ICollection<pedido> pedido { get; set; }
        public virtual ICollection<roteador> roteador { get; set; }
    }
}
