//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using WebApi2.Models.Formulario;
    
    public partial class EPEDIDOSEntities1 : DbContext
    {
        public EPEDIDOSEntities1()
            : base("name=EPEDIDOSEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<categoria> categoria { get; set; }
        public DbSet<evento> evento { get; set; }
        public DbSet<formulario> formulario { get; set; }
        public DbSet<pedido> pedido { get; set; }
        public DbSet<roteador> roteador { get; set; }
        public DbSet<Grupo> grupo { get; set; }
    }
}
