//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using WebApi2.Models.Formulario;
    
    public partial class pedido
    {
        public pedido()
        {
            this.evento = new HashSet<evento>();
        }

        [Key]
        public int Idn_Pedido { get; set; }
        public Nullable<int> Idn_Grupo { get; set; }
        public Nullable<int> Idn_Formulario { get; set; }
        public string Idn_Usuario { get; set; }
        public string Idn_Usuario_Responsavel { get; set; }
        public string Idn_Executor { get; set; }
        public string Dsc_Texto { get; set; }
        public string Dsc_Status { get; set; }
        public Nullable<System.DateTime> Dta_Pedido { get; set; }
        public string Dsc_Nome_Criador { get; set; }
        public string Dsc_Nome_Executor { get; set; }
        public string Dsc_Departamento { get; set; }
        public string Dsc_Endereco { get; set; }
        public string Dsc_Telefone { get; set; }
    
        public virtual ICollection<evento> evento { get; set; }
        public virtual formulario formulario { get; set; }
    }
}
