//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class PerfilUsuario
    {
        [Key]
        public long IDN_PERFIL { get; set; }
        public string COD_USUARIO { get; set; }
        public Nullable<System.DateTime> Dta_Inclusao { get; set; }
    
        public virtual Perfil Perfil { get; set; }
    }
}
